skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :users, only: [:new, :create]
  resource :session, only:[:new, :create, :destroy], :controller => 'session'

  root to: redirect('/cats')
end

skeleton/app/controllers/session_controller.rb
class SessionController < ApplicationController
  #verify user_name/password
  #reset the user's

  def new
    render :new
  end

  def create
    temp_params = user_params(params)
    user_password = temp_params[:password]
    user_name = temp_params[:username]
    @user = User.find_by_credentials(user_name, user_password)
    if @user
      @user.reset_session_token!
      session[:session_token] = @user.session_token
      redirect_to cats_url
    else

      redirect_to new_session_url
    end
  end


  def user_params(params)
    params.require(:user).permit(:username, :password)
  end

  def destroy
    if current_user
      current_user.reset_session_token!
      session[:session_token] = nil
    
    end
  end



end

skeleton/app/views/session/new.html.erb
<form action=" <%= session_url %>" method="POST">
  <!-- <input type="hidden" name="_method" value="POST"> -->

  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="username">Username</label>
    <input id="username" name="user[username]" type="text">

  <label for="password">Password</label>
    <input id="password" name="user[password]" type="password">

  <input type="submit" value="Submit">
</form>